### ISSUE TITLE
No logging by default

### ISSUE THREAD

**Issue by NathanSweet** [ZeroOne3010/yetanotherhueapi#50]
I like the library a lot, thank you! Just one minor quibble: the library does logging by default.

During discovery I see mDNS logging. Maybe there's a way to hide that, but it's not readily obvious.

While waiting for the bridge button press, the library prints a message to press the button. This doesn't match the logging of my app. I want to print my own message, but then I'd have two.

After that it seems I can connect and turn lights on/off without logging, so that's good.

I'd prefer if the library does not log anything by default. Having a way to turn it on would be OK. If something goes really wrong there's probably an exception with a message.

**Comment by ZeroOne3010** [comment]
Hi Nathan, thanks for your feedback! 😃  The project is using the java.util.logging system. [This blog post](https://alvinalexander.com/source-code/java/how-turn-off-disable-javautillogging-output-logmanager/) has an easy and working method to disable those logs altogether: `LogManager.getLogManager().reset();`. I just tried it, it seems to work. Apparently you can also control the log levels with a file called `logging.properties`, you might want to look into that as well.

The issue here is that the message that tells you to push the button is logged using .... `System.out.println`. 😑 Lame, I know! I'll change that to use the logger that you can then turn off. Would that work for you?

**Comment by NathanSweet** [comment]
`LogManager.getLogManager().reset();` seems to work. That kills all JUL logging, feels a bit extreme.

A `logging.properties` file has never been a good idea. Where to put it? What happens when there are multiple on the classpath? How to be sure mine is used? A JVM argument... noooo. They managed to make even logging hard! :p

This is slightly better:
```
Arrays.stream(LogManager.getLogManager().getLogger("").getHandlers()).forEach(h -> h.setLevel(Level.WARNING));
```
You'd think it'd be possible to get the specific logger and configure just that, but I couldn't figure it out.

That plus changing the sysout and I'm happy. :) Cheers!

**Comment by ZeroOne3010** [comment]
Version **2.6.0** is being deployed into the repository as I type. I've replaced System.outs with loggers, and unified all loggers to use the same name. You may test it now.
